name: HiFINI 自动签到

on:
  workflow_dispatch:
  #schedule:
    #- cron: "30 22 * * *" # 北京时间上午06:30

jobs:
  build:
    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Ant
        run: |
          mvn compile
          mvn exec:java -Dexec.mainClass="com.github.pengpan.App"
